on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: my.cloudron.dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Cloudron Push to App
        uses: cloudron-io/cloudron-push-to-app@latest
        with:
          CLOUDRON_TOKEN: "${{ secrets.CLOUDRON_URL }}"
          CLOUDRON_APP_ID: "${{ secrets.CLOUDRON_APP_ID }}"
          CLOUDRON_URL: "${{ secrets.CLOUDRON_TOKEN }}"
          CLOUDRON_PUSH_DESTINATION: "/app/data/public/"